Makefile
docs/terraform-controller/admin/policy.md
docs/terraform-controller/releases.md

Adding the docs for module selector which will be merged in v0.1.4

Module Selectors

---

docs/terraform-controller/developer/flux.md

Adding documentation on how to use a the flux source controller as a source for the modules

[DOCS] - Adding Flux Docs

---

Makefile
crdgen/config.yaml
docs/terraform-controller/reference/_category_.json
docs/terraform-controller/reference/policies.terraform.appvia.io.md

Updating the references for the api types

API CRD Reference

---

docs/terraform-controller/reference/policies.terraform.appvia.io.md

This will need to be removed from the api types comments itself, needs a release though

API References

---

Makefile
docs/terraform-controller/reference/_category_.json

Fixing the category on the side menu

API Reference Category

---

docs/terraform-controller/index.md

Updating the installation docs to reference using the released chart

Update Installation Docs

---

docs/terraform-controller/releases.md

Adding the release notes for v0.1.5

Updating Release Docs

---

docs/terraform-controller/index.md

The quickstart was no longer referencing the git clone - but much of the setup was

Quick Start Fixes

---

docs/terraform-controller/admin/drift.md
docs/terraform-controller/developer/drift.md
docs/terraform-controller/index.md

Adding the docs for drift detection

Drift Detection

---

docs/terraform-controller/admin/drift.md
docs/terraform-controller/admin/providers.md
docs/terraform-controller/developer/configuration.md
docs/terraform-controller/developer/drift.md
docs/terraform-controller/index.md
docs/terraform-controller/reference/configurations.terraform.appvia.io.md
docs/terraform-controller/reference/providers.terraform.appvia.io.md
docs/terraform-controller/releases.md

Adding the documentation and release notes for v0.2.0
- added the updates to the crd reference

Release v0.2.0

---

docs/terraform-controller/admin/providers.md
docs/terraform-controller/releases.md

Updating the docs related to the release

Updating the Release

---

docs/terraform-controller/releases.md

Adding the release notes for v0.2.3

Release v0.2.3

---

docs/terraform-controller/reference/providers.terraform.appvia.io.md

Updating the api reference with the changes

Update API Reference

---

docs/terraform-controller/releases.md

Adding the release notes v0.2.5

Release Notes

---

docusaurus.config.js

Changing the link back to the terraform-controller

Github Repository Link

---

src/pages/index.js

Dropping the splash screen for now until it's redesigned.

Dropping Splash Screen

---

docs/terraform-controller/admin/providers.md

Need to inform users of service account permissions for executors

Service Account Permissions

---

docs/terraform-controller/admin/policy.md

Fixing up the example given in the docs for defaults

Default Policy

---

docs/terraform-controller/workflows/intro.md
docs/terraform-controller/workflows/platform.md

Workflow Typos

---

docs/terraform-controller/releases.md

Adding the release notes for release v0.2.7

Release Notes v0.2.7

---

docs/terraform-controller/releases.md

Release Notes v0.2.8

---

Makefile
docs/terraform-controller/cli/tnctl.md
docs/terraform-controller/cli/tnctl_build.md
docs/terraform-controller/cli/tnctl_describe.md
docs/terraform-controller/cli/tnctl_logs.md
docs/terraform-controller/cli/tnctl_search.md
docs/terraform-controller/cli/tnctl_workflow_create.md

Updating the cli reference documentation

Updating CLI Reference

---

docs/terraform-controller/admin/providers.md
docs/terraform-controller/reference/providers.terraform.appvia.io.md
docs/terraform-controller/releases.md

- Release Notes v0.2.9
- - updated the crd reference for the v0.2.9 release

Release Notes - v0.2.9

---

docs/terranetes-controller/releases.md

Updated the release notes to use the renamed repository

Updating Release Notes

---

src/components/Products/index.js
src/pages/index.js

- fixed the redirect to /terranetes-controller

Fixing Redirect

---

docs/terranetes-controller/releases.md

Adding the updated release nodes

Release notes v0.3.0

---

docs/terranetes-controller/releases.md

Release v0.3.1

---

Makefile
docs/terranetes-controller/admin/state.md
docs/terranetes-controller/releases.md

Describe how the state is kept and how the platform can override to place the state in another location

Terraform State

---

docs/terranetes-controller/cli/tnctl.md
docs/terranetes-controller/cli/tnctl_kubectl.md
docs/terranetes-controller/cli/tnctl_kubectl_plugin.md
docs/terranetes-controller/developer/tnctl.md

Adding the updated CLI reference to include kubectl command and updating the developer section to reference.

Kubectl Integration Docs

---

docs/terranetes-controller/developer/tnctl.md

Adding more info on the developer documentation around the tnctl command

Developer Docs

---

docs/terranetes-controller/index.md

Just adding the same pitch as the docs on the repository

Updating Main Page

---

docs/terranetes-controller/cli/tnctl_search.md
docs/terranetes-controller/releases.md

Updating Releases

---

docs/terranetes-controller/developer/private.md

Adding some more details into regard to private modules

Adding Detail for Private Modules

---

docs/terranetes-controller/cli/tnctl.md
docs/terranetes-controller/cli/tnctl_convert.md
docs/terranetes-controller/cli/tnctl_convert_configuration.md
docs/terranetes-controller/releases.md

Updating the releases to include 0.3.5 and 0.3.6, also updating the CLI docs to include
the convert command

Updating Releases & CLI Docs

---

src/css/custom.css

On my 4k screen the hero banner creates a huge gap between the banner and the features

Tweaking the Hero Banner

---

docs/terranetes-controller/admin/policy/checkov.md
docs/terranetes-controller/releases.md

Adding the changes for the v0.3.8 release

Release v0.3.8

---

docs/terranetes-controller/releases.md

Adding the notes for the release

Release v0.3.9

---

docs/terranetes-controller/releases.md

Release Notes v0.3.10

---

docs/terranetes-controller/developer/configuration.md

A few minor changes to the developer docs and highlighting the tnctl command

Developer Docs Changes

---

docs/terranetes-controller/releases.md

Adding the changelog for the release

Release v0.3.11

---

docusaurus.config.js

Just changing the header title

Changed Header from "Terranetes Controller" to "Docs"

---

docs/terranetes-controller/releases.md

Release Notes v0.3.12

---

docs/terranetes-controller/releases.md

Release Note 0.3.13

---

docs/terranetes-controller/cli/tnctl.md
docs/terranetes-controller/cli/tnctl_kubectl_plugin.md
docs/terranetes-controller/cli/tnctl_logs.md
docs/terranetes-controller/cli/tnctl_retry.md
docs/terranetes-controller/cli/tnctl_search.md
docs/terranetes-controller/cli/tnctl_state.md
docs/terranetes-controller/cli/tnctl_state_clean.md
docs/terranetes-controller/cli/tnctl_state_list.md

Updating the reference documentation for the tnctl CLI

Updating CLI Reference Docs

---

docs/terranetes-controller/admin/policy/defaults.md
docs/terranetes-controller/admin/secrets.md

Adding some docs on default secret injection

Adding Docs on Default Secret Injection

---

docs/terranetes-controller/releases.md

Release Docs

---

docs/terranetes-controller/admin/defaults.md

Altering the location and docs around injection of defaults

Injecting Defaults

---

docs/terranetes-controller/admin/providers.md

Adding the documentation for default provider annotation

Default Provider

---

docs/terranetes-controller/reference/configurations.terraform.appvia.io.md
docs/terranetes-controller/reference/policies.terraform.appvia.io.md

Updating the CRD reference documentation

CRD Reference

---

docs/terranetes-controller/developer/private.md

Private Repos

---

docs/terranetes-controller/admin/state.md

Updating the terraform state variables

Terraform State Variable

---

docs/terranetes-controller/admin/protect.md
docs/terranetes-controller/reference/configurations.terraform.appvia.io.md
docs/terranetes-controller/reference/providers.terraform.appvia.io.md

Updating the CRD references in the docs

Update CRD Reference

---

crdgen/config.yaml
docs/terranetes-controller/admin/contexts.md
docs/terranetes-controller/admin/protect.md
docs/terranetes-controller/developer/contexts.md
docs/terranetes-controller/reference/contexts.terraform.appvia.io.md

Addig docs around Contexts for admins and developers

Contexts Documentation

---

docs/terranetes-controller/admin/state.md

Adding the updated docs for backend state configuration

Backend State Configuration

---

docs/terranetes-controller/admin/contexts.md

Updating the docs slightly in relation to context, custom preloads and so forth

Additional Configuration Context Docs

---

docs/terranetes-controller/walkthroughs/_category_.json
docs/terranetes-controller/walkthroughs/database.md

Adding a walkthrough for the rds

Walkthrough for RDS

---

docs/terranetes-controller/admin/providers.md

Adding docs to Azure AAD Identity provider

Azure Identity Provider

---

docs/terranetes-controller/admin/defaults.md

Adding a note on the bug related to defaults and secrets

Secret Defaults Note

---

docs/terranetes-controller/admin/providers.md

Azure Provider Docs

---

package-lock.json
package.json

Updating the dependencies for the doc site

Updating Docs Site
